language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
  